apiVersion: v1
kind: Service
metadata:
  name: food-delivery-service
spec:
  type: NodePort
  selector:
    app: food-delivery-app
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30081
